Traceback (most recent call last):
  File "c:\Users\alyss\OneDrive\Área de Trabalho\SOMN\Treinamento.py", line 71, in <module>
    model.learn(total_timesteps=3328*1000)
  File "c:\Users\alyss\OneDrive\Área de Trabalho\SOMN\Stable_baselines3\PPO.py", line 440, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "c:\Users\alyss\OneDrive\Área de Trabalho\SOMN\Stable_baselines3\OnPolicyAlgirithm.py", line 262, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alyss\OneDrive\Área de Trabalho\SOMN\Stable_baselines3\OnPolicyAlgirithm.py", line 179, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 197, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 70, in step_wait
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\stable_baselines3\common\monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alyss\OneDrive\Área de Trabalho\SOMN\Ambiente_SOMN\Somn.py", line 570, in reset
    plt.savefig(f'figuras/teste{self.contador}.png', format='png')
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\matplotlib\pyplot.py", line 1119, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\matplotlib\figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\matplotlib\backend_bases.py", line 2187, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\matplotlib\backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\matplotlib\backends\backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\matplotlib\backends\backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\matplotlib\image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Users\alyss\OneDrive\Área de Trabalho\SOMN\.venv\Lib\site-packages\PIL\Image.py", line 2350, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'figuras/teste0.png'